In [3]:
# -*- coding: utf-8 -*-
# Indentation: Jupyter Notebook

'''
sklearn exploration
'''

__version__ = 1.0
__author__ = "Sourav Raj"
__author_email__ = "souravraj.iitbbs@gmail.com"


In [1]:
from sklearn.datasetssets import load_iris
iris = load_iris()

In [5]:
x=iris.data

In [3]:
y=iris.target

In [8]:
import pandas as pd
pd.DataFrame(x, columns=iris.feature_names).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [12]:
knn.predict([[3,5,4,2]])

C:\ProgramData\Anaconda2\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

# Representing text as numeric data

In [13]:
simple_train = ['call you tonight', 'Call me a cab', 'please call me...']


In [14]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [17]:
# fit to vocubalary
vect.fit(simple_train)

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [16]:
vect.get_feature_names()

[u'cab', u'call', u'me', u'please', u'tonight', u'you']

In [18]:
# transform training data into a document-term-matrix
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<3x6 sparse matrix of type '<type 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [20]:
# convert to dense matrix from spars matrix
simple_train_dtm.toarray()
# row - no of document, column - no of feature

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0]], dtype=int64)

In [21]:
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       1        0    0

In [22]:
type(simple_train_dtm)

scipy.sparse.csr.csr_matrix

In [23]:
print(simple_train_dtm)

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	1


In [32]:
simple_test = ["please don't call me"]

In [33]:
simple_test_dtm = vect.transform(simple_test)

In [34]:
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]], dtype=int64)

In [35]:
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   1       1        0    0

In [47]:
url = 'https://github.com/justmarkham/pycon-2016-tutorial/blob/master/data/sms.tsv'

In [50]:
path = "C:/Users/sourav.raj.IN/Documents/Python Scripts/learn/sms.tsv"

In [58]:
sms = pd.read_table(path, header=None, names=['label', 'message'])

In [59]:
sms.shape

(5572, 2)

In [60]:
sms.head(10)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [62]:
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [63]:
sms['label_num'] = sms.label.map({'ham':0, 'spam':1})

In [64]:
sms.head(10)

label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0
5  spam  FreeMsg Hey there darling it's been 3 week's n...          1
6   ham  Even my brother is not like to speak with me. ...          0
7   ham  As per your request 'Melle Melle (Oru Minnamin...          0
8  spam  WINNER!! As a valued network customer you have...          1
9  spam  Had your mobile 11 months or more? U R entitle...          1

In [66]:
x = sms.message
y = sms.label_num
print(x.shape)
print(y.shape)

(5572L,)
(5572L,)


In [67]:
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1)

In [68]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


(4179L,)
(1393L,)
(4179L,)
(1393L,)


In [69]:
vect = CountVectorizer()
vect.fit(x_train)

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [71]:
x_train_dtm = vect.transform(x_train)
# or x_train_dtm = vect.fit_transform(x_train)

In [72]:
x_train_dtm

<4179x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [73]:
x_test_dtm = vect.transform(x_test)
x_test_dtm

<1393x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

In [74]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [75]:
%time nb.fit(x_train_dtm, y_train)

Wall time: 18 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [76]:
y_pred_class = nb.predict(x_test_dtm)

In [77]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.98851399856424982

In [79]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[1203,    5],
       [  11,  174]])

In [81]:
# print msg for the false positive
x_test[(y_pred_class==1) & (y_test==0)]
x_test[y_pred_class > y_test]

574               Waiting for your call.
3375             Also andros ice etc etc
45      No calls..messages..missed calls
3415             No pic. Please re-send.
1988    No calls..messages..missed calls
Name: message, dtype: object

In [82]:
# print msg for the false negative
x_test[y_pred_class < y_test]

3132    LookAtMe!: Thanks for your purchase of a video...
5       FreeMsg Hey there darling it's been 3 week's n...
3530    Xmas & New Years Eve tickets are now on sale f...
684     Hi I'm sue. I am 20 years old and work as a la...
1875    Would you like to see my XXX pics they are so ...
1893    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
4298    thesmszone.com lets you send free anonymous an...
4949    Hi this is Amy, we will be sending you a free ...
2821    INTERFLORA - “It's not too late to order Inter...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
4514    Money i have won wining number 946 wot do i do...
Name: message, dtype: object

In [83]:
x_test[3132]

"LookAtMe!: Thanks for your purchase of a video clip from LookAtMe!, you've been charged 35p. Think you can do better? Why not send a video in a MMSto 32323."

In [84]:
y_pred_prob = nb.predict_proba(x_test_dtm)[:,1]

In [85]:
y_pred_prob

array([  2.87744864e-03,   1.83488846e-05,   2.07301295e-03, ...,
         1.09026171e-06,   1.00000000e+00,   3.98279868e-09])

In [86]:
metrics.roc_auc_score(y_test, y_pred_prob)

0.98664310005369615

#Comparing models

In [87]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [88]:
%time logreg.fit(x_train_dtm, y_train)

Wall time: 470 ms


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [91]:
y_pred_class = logreg.predict(x_test_dtm)

In [92]:
y_pred_prob = logreg.predict_proba(x_test_dtm)[:, 1]

In [93]:
metrics.accuracy_score(y_test, y_pred_class)

0.9877961234745154

In [94]:
metrics.roc_auc_score(y_test, y_pred_prob)

0.99368176123143015

In [95]:
#Examine the model for further insight

In [96]:
x_train_tokens = vect.get_feature_names()
len(x_train_tokens)

7456

In [98]:
print x_train_tokens[0:50]

[u'00', u'000', u'008704050406', u'0121', u'01223585236', u'01223585334', u'0125698789', u'02', u'0207', u'02072069400', u'02073162414', u'02085076972', u'021', u'03', u'04', u'0430', u'05', u'050703', u'0578', u'06', u'07', u'07008009200', u'07090201529', u'07090298926', u'07123456789', u'07732584351', u'07734396839', u'07742676969', u'0776xxxxxxx', u'07781482378', u'07786200117', u'078', u'07801543489', u'07808', u'07808247860', u'07808726822', u'07815296484', u'07821230901', u'07880867867', u'0789xxxxxxx', u'07946746291', u'0796xxxxxx', u'07973788240', u'07xxxxxxxxx', u'08', u'0800', u'08000407165', u'08000776320', u'08000839402', u'08000930705']


In [100]:
print x_train_tokens[-50:]

[u'yer', u'yes', u'yest', u'yesterday', u'yet', u'yetunde', u'yijue', u'ym', u'ymca', u'yo', u'yoga', u'yogasana', u'yor', u'yorge', u'you', u'youdoing', u'youi', u'youphone', u'your', u'youre', u'yourjob', u'yours', u'yourself', u'youwanna', u'yowifes', u'yoyyooo', u'yr', u'yrs', u'ything', u'yummmm', u'yummy', u'yun', u'yunny', u'yuo', u'yuou', u'yup', u'zac', u'zaher', u'zealand', u'zebra', u'zed', u'zeros', u'zhong', u'zindgi', u'zoe', u'zoom', u'zouk', u'zyada', u'\xe8n', u'\u3028ud']


In [101]:
nb.feature_count_

array([[  0.,   0.,   0., ...,   1.,   1.,   1.],
       [  5.,  23.,   2., ...,   0.,   0.,   0.]])

In [102]:
nb.feature_count_.shape

(2L, 7456L)

In [104]:
ham_token_count = nb.feature_count_[0,:]
ham_token_count

array([ 0.,  0.,  0., ...,  1.,  1.,  1.])

In [107]:
spam_token_count = nb.feature_count_[1,:]
spam_token_count


array([  5.,  23.,   2., ...,   0.,   0.,   0.])

In [109]:
tokens = pd.DataFrame({'token':x_train_tokens, 'ham':ham_token_count, 'spam': spam_token_count })

In [110]:
tokens.head()

ham  spam         token
0  0.0   5.0            00
1  0.0  23.0           000
2  0.0   2.0  008704050406
3  0.0   1.0          0121
4  0.0   1.0   01223585236

In [111]:
tokens.sample(5, random_state=6)

ham  spam         token
6977  64.0   2.0          very
4521   1.0   1.0         nasty
6999   0.0   1.0         villa
1266   1.0   0.0       beloved
6522   0.0   2.0  textoperator

In [112]:
nb.class_count_

array([ 3617.,   562.])

In [113]:
tokens.ham = tokens.ham+1
tokens.spam = tokens.spam +1
tokens.sample(5, random_state=6)

ham  spam         token
6977  65.0   3.0          very
4521   2.0   2.0         nasty
6999   1.0   2.0         villa
1266   2.0   1.0       beloved
6522   1.0   3.0  textoperator

In [114]:
tokens.ham = tokens.ham/nb.class_count_[0]
tokens.spam = tokens.spam / nb.class_count_[1]
tokens.sample(5, random_state=6)

ham      spam         token
6977  0.017971  0.005338          very
4521  0.000553  0.003559         nasty
6999  0.000276  0.003559         villa
1266  0.000553  0.001779       beloved
6522  0.000276  0.005338  textoperator

In [118]:
tokens['spam_ratio'] = tokens.spam/tokens.ham
tokens.sample(5, random_state=6)

ham      spam         token  spam_ratio
6977  0.017971  0.005338          very    0.297044
4521  0.000553  0.003559         nasty    6.435943
6999  0.000276  0.003559         villa   12.871886
1266  0.000553  0.001779       beloved    3.217972
6522  0.000276  0.005338  textoperator   19.307829

In [119]:
tokens.sort_values('spam_ratio', ascending=False)

ham      spam       token  spam_ratio
1766  0.000276  0.158363       claim  572.798932
5209  0.000276  0.135231       prize  489.131673
293   0.000276  0.087189        150p  315.361210
6680  0.000276  0.085409        tone  308.925267
3139  0.000276  0.076512  guaranteed  276.745552
307   0.000276  0.069395          18  251.001779
2022  0.000276  0.065836          cs  238.129893
7357  0.000553  0.129893         www  234.911922
246   0.000276  0.056940        1000  205.950178
1130  0.000276  0.053381     awarded  193.078292
297   0.000276  0.051601      150ppm  186.642349
6829  0.000553  0.099644          uk  180.206406
521   0.000276  0.048043         500  173.770463
5558  0.000276  0.044484    ringtone  160.898577
1     0.000276  0.042705         000  154.462633
4371  0.000276  0.042705         mob  154.462633
1810  0.000553  0.078292          co  141.590747
1834  0.000276  0.039146  collection  141.590747
6947  0.000276  0.037367       valid  135.154804
336   0.000276  0.037367        2000  135.154804
617   0.000276  0.037367         800  135.154804
254   0.000276  0.037367         10p  135.154804
620   0.000276  0.035587        8007  128.718861
302   0.000553  0.067616          16  122.282918
7147  0.000276  0.033808      weekly  122.282918
6681  0.000276  0.032028       tones  115.846975
3856  0.000276  0.032028        land  115.846975
3402  0.000276  0.032028        http  115.846975
4527  0.000276  0.030249    national  109.411032
522   0.000276  0.030249        5000  109.411032
...        ...       ...         ...         ...
7166  0.012718  0.001779        went    0.139912
4006  0.052530  0.007117          ll    0.135494
6670  0.013824  0.001779        told    0.128719
2695  0.013824  0.001779        feel    0.128719
3141  0.014100  0.001779         gud    0.126195
1950  0.014929  0.001779         cos    0.119184
1522  0.090683  0.010676         but    0.117731
920   0.015206  0.001779         amp    0.117017
6040  0.015206  0.001779   something    0.117017
6355  0.015206  0.001779        sure    0.117017
4727  0.061100  0.007117          ok    0.116488
5644  0.016312  0.001779        said    0.109084
4417  0.016865  0.001779     morning    0.105507
7396  0.017694  0.001779        yeah    0.100562
4029  0.017694  0.001779         lol    0.100562
967   0.017971  0.001779    anything    0.099015
4489  0.150401  0.014235          my    0.094646
2313  0.019077  0.001779       doing    0.093275
7115  0.019630  0.001779         way    0.090647
1060  0.019630  0.001779         ask    0.090647
897   0.019630  0.001779     already    0.090647
6689  0.021841  0.001779         too    0.081468
1843  0.048936  0.003559        come    0.072723
3879  0.030688  0.001779       later    0.057981
4051  0.032900  0.001779         lor    0.054084
2066  0.032900  0.001779          da    0.054084
5824  0.035665  0.001779         she    0.049891
3244  0.047000  0.001779          he    0.037858
4093  0.064142  0.001779          lt    0.027741
3135  0.064971  0.001779          gt    0.027387

[7456 rows x 4 columns]

In [121]:
tokens.loc['awarded', 'spam_ratio']

KeyError: 'the label [awarded] is not in the [index]'

# Tunning the Vector parameter 



In [122]:
vect

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [123]:
#imp parameters for tunning:
# 1) stop_words : words which are not usefull for model.. commomnly used word
# 2) ngram_range : tuple(min_n, max_n), default = (1,1) : "not happy"
# include 1-grams and 2-grams
vect = CountVectorizer(ngram_range=(1,2))

In [ ]:
# 3) max_df: if word is too common then we want to remove it..
# 0.5 means if word appears in  50% of the documnetn .. 
#remove it 
vect = CountVectorizer(max_df=0.5)

In [ ]:
# 4) min_df:  