In [1]:
# -*- coding: utf-8 -*-
# Indentation: Visual Studio

'''
create square class using Polygon class
'''

__version__ = 1.0
__author__ = "Sourav Raj"
__author_email__ = "souravraj.iitbbs@gmail.com"


### Import Numpy

In [2]:
import numpy as np



### numpy arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

#### Creating NumPy Arrays

From a List

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

There are lots of built-in ways to generate arrays.

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
Return evenly spaced numbers over a specified interval. [[reference](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [9]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [10]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>Note that `.linspace()` *includes* the stop value. To obtain an array of common fractions, increase the number of items:</font>

In [11]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 
Numpy also has lots of ways to create random number arrays:

### rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [13]:
np.random.rand(2)

array([0.93718497, 0.55651969])

In [14]:
np.random.rand(5,5)

array([[0.12732062, 0.99299754, 0.37046981, 0.83120757, 0.16079098],
       [0.45892553, 0.18401431, 0.45899921, 0.70181304, 0.76208532],
       [0.95938188, 0.75731217, 0.26600498, 0.45252159, 0.20288464],
       [0.39356654, 0.44196121, 0.47019314, 0.49492023, 0.57352161],
       [0.31902232, 0.40601927, 0.74744622, 0.91564356, 0.26100422]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [15]:
np.random.randn(2)

array([-1.13212104,  0.62632677])

In [16]:
np.random.randn(5,5)

array([[ 0.52678987, -0.79015549,  0.09550182, -0.70499835,  0.22926733],
       [-0.14111014, -1.08636129, -0.02590336,  0.99566444,  0.71129717],
       [-0.71092134,  0.01648667, -1.04219774,  0.28119947, -1.63548767],
       [-0.23763559,  1.22626092,  0.55635736,  0.73077858,  0.57680591],
       [ 0.26933982, -0.51499098,  0.0338899 ,  0.71724498, -0.12312663]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [17]:
np.random.randint(1,100)

55

In [18]:
np.random.randint(1,100,10)

array([96, 77, 27, 77, 81, 21, 16, 41, 24, 67])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [21]:
np.random.seed(42)
np.random.rand(2)

array([0.37454012, 0.95071431])

In [22]:
np.random.seed(42)
np.random.rand(2)

array([0.37454012, 0.95071431])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([42,  7, 20, 38, 18, 22, 10, 10, 23, 35])

## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
ranarr

array([42,  7, 20, 38, 18, 22, 10, 10, 23, 35])

In [29]:
ranarr.max()

42

In [30]:
ranarr.argmax()

0

In [31]:
ranarr.min()

7

In [32]:
ranarr.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [33]:
# Vector
arr.shape

(25,)

In [34]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

In [36]:
print(arr.reshape(25,1))

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]


In [37]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [38]:
arr.dtype

dtype('int32')

In [39]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')